services:
  - type: web
    name: barber-backend
    env: node
    rootDir: barber-server
    buildCommand: "npm install"
    startCommand: "npm start"
    plan: free
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: DB_CLIENT
        value: postgres
      - key: DATABASE_URL
        fromDatabase:
          name: barber-postgres
          property: connectionString

databases:
  - name: barber-postgres
    plan: free
